# notifications settings
notifications:
    # from
    from:
        name: Stefan
        email: contact@stefanolaru.com
    # subject
    subject:
        fail: 🚨 Outage detected
        pass: ✅ All is back to normal
    # who to alert
    email:
        - olaroost@gmail.com

# the pages to be checked
# update the timeout of the lambda function if you have any pages
pages:
    # this will fail
    - url: https://placehold.it/600x400
      name: Placehold It
    # this will pass
    - url: https://crafty.ro
      maxRedirects: 1
    # minimum example
    - url: https://google.com
      maxRedirects: 1
