service: uptimemonitor

custom:
    defaultStage: dev
    environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}

provider:
    name: aws
    # local aws profile -- to be removed
    profile: uptimemonitor
    # stage
    stage: ${opt:stage, self:custom.defaultStage}
    runtime: nodejs14.x
    tags:
        project: uptimemonitor
    environment:
        APP_NAME: ${self:custom.environment.name}

functions:
    # the checker function
    check:
        handler: src/check.handler
        memorySize: 256
        timeout: 30
        environment:
            DDB_LOGS_TABLE: !Ref uptimeMonitorLogsTable
            AWS_KEY: !Ref uptimeMonitorAccessKeys
            AWS_SECRET: !GetAtt uptimeMonitorAccessKeys.SecretAccessKey
            SNS_TOPIC: !Ref uptimeMonitorSNSTopic
            SES_TEMPLATE: !Ref uptimeMonitorEmailTemplate
        events:
            - schedule: rate(5 minutes)

    # email recipient validator, can only be triggered directly
    validate:
        handler: src/validate-sender.handler
        environment:
            AWS_KEY: !Ref uptimeMonitorAccessKeys
            AWS_SECRET: !GetAtt uptimeMonitorAccessKeys.SecretAccessKey

package:
    # exclude files from the package
    exclude:
        - sample-env.yml
        - package.json
        - package-lock.json
        - README.md
        - LICENSE
        - email/**

plugins:
    - serverless-offline

resources: # CloudFormation template syntax
    Resources:
        # the logs table
        uptimeMonitorLogsTable:
            Type: AWS::DynamoDB::Table
            # DeletionPolicy: Retain
            Properties:
                TableName: ${self:custom.environment.logs_table}
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: created_at
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                    - AttributeName: created_at
                      KeyType: RANGE
                # use the On Demand pricing
                BillingMode: PAY_PER_REQUEST
                # autodelete logs after specified time
                TimeToLiveSpecification:
                    AttributeName: expires_at
                    Enabled: TRUE

        # create the IAM user that will be asigned to the policy
        uptimeMonitorUser:
            Type: AWS::IAM::User
            Properties:
                UserName: ${self:custom.environment.username}
                Policies:
                    - PolicyName: uptimeMonitorIAMPolicy
                      PolicyDocument:
                          Version: "2012-10-17"
                          Statement:
                              - Effect: "Allow"
                                Action:
                                    - "ses:*"
                                    - "dynamodb:*"
                                    - "sns:*"
                                Resource: "*"

        # create the access keys for the IAM user
        uptimeMonitorAccessKeys:
            Type: AWS::IAM::AccessKey
            Properties:
                UserName: !Ref uptimeMonitorUser

        # create the SNS topic to receive the results
        uptimeMonitorSNSTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: ${self:custom.environment.sns_topic}

        # create the SES notification template
        uptimeMonitorEmailTemplate:
            Type: AWS::SES::Template
            Properties:
                Template:
                    TemplateName: uptimeMonitorNotificationEmail
                    SubjectPart: "{{subject}}"
                    TextPart: ${file(email/notification.txt)}
                    HtmlPart: ${file(email/notification.html)}
